# INTRODUCTION TO NUMPY

In [2]:
import numpy as np

## Creating arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1.5,5.6,8.9,9.0])
a

array([1.5, 5.6, 8.9, 9. ])

In [11]:
a[2] = 10
a[2]

10.0

In [13]:
np.arange(2,5)

array([2, 3, 4])

## Multidimensional arrays

In [3]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [96]:
n[:,0]
#n[0]
#n

array([1, 4, 0])

In [18]:
n[2] = np.zeros(3)
n[:,1]

array([2, 5, 0])

## Ramdonly generated arrays


In [35]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
np.random.seed(2)
100 * np.random.randint(low=0,high=100, size=(5,2))

array([[4000, 1500],
       [7200, 2200],
       [4300, 8200],
       [7500,  700],
       [3400, 4900]])

## Element-wise operations

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
a * 2

array([0, 2, 4, 6, 8])

In [44]:
b = (10 + (a * 2))  ** 2 / 100

In [45]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [46]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [47]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [48]:
a >= 2

array([False, False,  True,  True,  True])

In [50]:
a [a > b]

array([2, 3, 4])

## Summarizing operations

In [52]:
b.min()

1.0

In [53]:
a.max()

4

In [54]:
a.sum()

10

In [55]:
a.mean()

2.0

In [57]:
a.std()

1.4142135623730951

## Vector operations

In [98]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],         
]) 
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
]) 

In [61]:
def dot_product(a,b):
    assert a.shape[0] == b.shape[0]
    
    n = a.shape[0]
    result = 0.0

    for i in range(n):
        result = result + a[i] * b[i]

    return result

In [83]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    n = U.shape[0]

    result = np.zeros(n)

    for i in range(n):
        result[i] = dot_product(U[i],v)

    return result

In [86]:
matrix_vector_multiplication(V,v)

array([14.,  5.,  5.])

In [90]:
V.dot(v)

array([14,  5,  5])

In [67]:
dot_product(u,v)

14.0

In [64]:
v.dot(u)

14

In [105]:
def matix_matrix_multiplication(U,V):
    assert U.shape[0] == V.shape[1]

    n_rows = U.shape[0]
    n_colums = V.shape[1]

    result = np.zeros((n_rows,n_colums))

    for i in range(n_colums):
        result[:,i] = matrix_vector_multiplication(U,V[:,i])

    return result

In [106]:
matix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [107]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [114]:
# Identity matrix
I = np.eye(4)
I
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [113]:
U.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [124]:
Vs = V[0:3]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [121]:
np.linalg.inv(Vs)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [125]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])